name = "qstash-edge-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "URLS"
id = "5949fb525ffc4b49ade8de73c4db1a21"
preview_id = "17439a37a4c04b5d9284c96ab39bc78d"